name: Continuous Integration and Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  sample-dotnet:
    runs-on: linux-apache
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: dotnet info
        run: sudo dotnet --info

      - name: restore 
        run: dotnet restore

      - name: build 
        run: dotnet build -c Release --no-restore